/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthLoginResponse model module.
 * @module model/AuthLoginResponse
 * @version 0.0.1
 */
export class AuthLoginResponse {
  /**
   * Constructs a new <code>AuthLoginResponse</code>.
   * @alias module:model/AuthLoginResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthLoginResponse} obj Optional instance to populate.
   * @return {module:model/AuthLoginResponse} The populated <code>AuthLoginResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthLoginResponse();
      if (data.hasOwnProperty('jwt'))
        obj.jwt = ApiClient.convertToType(data['jwt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} jwt
 */
AuthLoginResponse.prototype.jwt = undefined;

