/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthWhoAmIResponse model module.
 * @module model/AuthWhoAmIResponse
 * @version 0.0.1
 */
export class AuthWhoAmIResponse {
  /**
   * Constructs a new <code>AuthWhoAmIResponse</code>.
   * @alias module:model/AuthWhoAmIResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthWhoAmIResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthWhoAmIResponse} obj Optional instance to populate.
   * @return {module:model/AuthWhoAmIResponse} The populated <code>AuthWhoAmIResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthWhoAmIResponse();
      if (data.hasOwnProperty('emai'))
        obj.emai = ApiClient.convertToType(data['emai'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('org_id'))
        obj.orgId = ApiClient.convertToType(data['org_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} emai
 */
AuthWhoAmIResponse.prototype.emai = undefined;

/**
 * @member {String} id
 */
AuthWhoAmIResponse.prototype.id = undefined;

/**
 * @member {String} orgId
 */
AuthWhoAmIResponse.prototype.orgId = undefined;

