/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthLogin model module.
 * @module model/AuthLogin
 * @version 0.0.1
 */
export class AuthLogin {
  /**
   * Constructs a new <code>AuthLogin</code>.
   * @alias module:model/AuthLogin
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthLogin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthLogin} obj Optional instance to populate.
   * @return {module:model/AuthLogin} The populated <code>AuthLogin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthLogin();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
AuthLogin.prototype.email = undefined;

/**
 * @member {String} password
 */
AuthLogin.prototype.password = undefined;

