/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GptCreateData} from './GptCreateData';

/**
 * The GptCreate model module.
 * @module model/GptCreate
 * @version 0.0.1
 */
export class GptCreate {
  /**
   * Constructs a new <code>GptCreate</code>.
   * @alias module:model/GptCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GptCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GptCreate} obj Optional instance to populate.
   * @return {module:model/GptCreate} The populated <code>GptCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GptCreate();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [GptCreateData]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/GptCreateData>} data
 */
GptCreate.prototype.data = undefined;

