/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GptCreateData model module.
 * @module model/GptCreateData
 * @version 0.0.1
 */
export class GptCreateData {
  /**
   * Constructs a new <code>GptCreateData</code>.
   * @alias module:model/GptCreateData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GptCreateData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GptCreateData} obj Optional instance to populate.
   * @return {module:model/GptCreateData} The populated <code>GptCreateData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GptCreateData();
      if (data.hasOwnProperty('requirements'))
        obj.requirements = ApiClient.convertToType(data['requirements'], ['String']);
      if (data.hasOwnProperty('tag'))
        obj.tag = ApiClient.convertToType(data['tag'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} requirements
 */
GptCreateData.prototype.requirements = undefined;

/**
 * @member {String} tag
 */
GptCreateData.prototype.tag = undefined;

