/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KbUpdate model module.
 * @module model/KbUpdate
 * @version 0.0.1
 */
export class KbUpdate {
  /**
   * Constructs a new <code>KbUpdate</code>.
   * @alias module:model/KbUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KbUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KbUpdate} obj Optional instance to populate.
   * @return {module:model/KbUpdate} The populated <code>KbUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KbUpdate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
KbUpdate.prototype.name = undefined;

