/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Org model module.
 * @module model/Org
 * @version 0.0.1
 */
export class Org {
  /**
   * Constructs a new <code>Org</code>.
   * @alias module:model/Org
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Org</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Org} obj Optional instance to populate.
   * @return {module:model/Org} The populated <code>Org</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Org();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
Org.prototype.description = undefined;

/**
 * @member {String} email
 */
Org.prototype.email = undefined;

/**
 * @member {String} id
 */
Org.prototype.id = undefined;

