/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrgTagInner} from './OrgTagInner';

/**
 * The OrgTag model module.
 * @module model/OrgTag
 * @version 0.0.1
 */
export class OrgTag extends Array {
  /**
   * Constructs a new <code>OrgTag</code>.
   * @alias module:model/OrgTag
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>OrgTag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrgTag} obj Optional instance to populate.
   * @return {module:model/OrgTag} The populated <code>OrgTag</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrgTag();
      ApiClient.constructFromObject(data, obj, 'OrgTagInner');
    }
    return obj;
  }
}
