/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrgUserInner model module.
 * @module model/OrgUserInner
 * @version 0.0.1
 */
export class OrgUserInner {
  /**
   * Constructs a new <code>OrgUserInner</code>.
   * @alias module:model/OrgUserInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrgUserInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrgUserInner} obj Optional instance to populate.
   * @return {module:model/OrgUserInner} The populated <code>OrgUserInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrgUserInner();
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('is_terms_conditions'))
        obj.isTermsConditions = ApiClient.convertToType(data['is_terms_conditions'], 'Boolean');
      if (data.hasOwnProperty('orgs_id'))
        obj.orgsId = ApiClient.convertToType(data['orgs_id'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('teams_id'))
        obj.teamsId = ApiClient.convertToType(data['teams_id'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Date} createdAt
 */
OrgUserInner.prototype.createdAt = undefined;

/**
 * @member {String} email
 */
OrgUserInner.prototype.email = undefined;

/**
 * @member {String} id
 */
OrgUserInner.prototype.id = undefined;

/**
 * @member {Boolean} isTermsConditions
 */
OrgUserInner.prototype.isTermsConditions = undefined;

/**
 * @member {String} orgsId
 */
OrgUserInner.prototype.orgsId = undefined;

/**
 * @member {String} status
 */
OrgUserInner.prototype.status = undefined;

/**
 * @member {String} teamsId
 */
OrgUserInner.prototype.teamsId = undefined;

/**
 * @member {Date} updatedAt
 */
OrgUserInner.prototype.updatedAt = undefined;

