/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TagManyResponse model module.
 * @module model/TagManyResponse
 * @version 0.0.1
 */
export class TagManyResponse {
  /**
   * Constructs a new <code>TagManyResponse</code>.
   * @alias module:model/TagManyResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TagManyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagManyResponse} obj Optional instance to populate.
   * @return {module:model/TagManyResponse} The populated <code>TagManyResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagManyResponse();
      if (data.hasOwnProperty('inserted'))
        obj.inserted = ApiClient.convertToType(data['inserted'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} inserted
 */
TagManyResponse.prototype.inserted = undefined;

