/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TagManyCreate model module.
 * @module model/TagManyCreate
 * @version 0.0.1
 */
export class TagManyCreate {
  /**
   * Constructs a new <code>TagManyCreate</code>.
   * @alias module:model/TagManyCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TagManyCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagManyCreate} obj Optional instance to populate.
   * @return {module:model/TagManyCreate} The populated <code>TagManyCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagManyCreate();
      if (data.hasOwnProperty('org_id'))
        obj.orgId = ApiClient.convertToType(data['org_id'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} orgId
 */
TagManyCreate.prototype.orgId = undefined;

/**
 * @member {Array.<String>} tags
 */
TagManyCreate.prototype.tags = undefined;

