/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TeamUserInner model module.
 * @module model/TeamUserInner
 * @version 0.0.1
 */
export class TeamUserInner {
  /**
   * Constructs a new <code>TeamUserInner</code>.
   * @alias module:model/TeamUserInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TeamUserInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamUserInner} obj Optional instance to populate.
   * @return {module:model/TeamUserInner} The populated <code>TeamUserInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamUserInner();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
TeamUserInner.prototype.email = undefined;

/**
 * @member {String} id
 */
TeamUserInner.prototype.id = undefined;

