/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TeamCreate model module.
 * @module model/TeamCreate
 * @version 0.0.1
 */
export class TeamCreate {
  /**
   * Constructs a new <code>TeamCreate</code>.
   * @alias module:model/TeamCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TeamCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamCreate} obj Optional instance to populate.
   * @return {module:model/TeamCreate} The populated <code>TeamCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamCreate();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('org_id'))
        obj.orgId = ApiClient.convertToType(data['org_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
TeamCreate.prototype.description = undefined;

/**
 * @member {String} name
 */
TeamCreate.prototype.name = undefined;

/**
 * @member {String} orgId
 */
TeamCreate.prototype.orgId = undefined;

