/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrgTeamInner} from './OrgTeamInner';

/**
 * The TeamKB model module.
 * @module model/TeamKB
 * @version 0.0.1
 */
export class TeamKB extends Array {
  /**
   * Constructs a new <code>TeamKB</code>.
   * @alias module:model/TeamKB
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TeamKB</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamKB} obj Optional instance to populate.
   * @return {module:model/TeamKB} The populated <code>TeamKB</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamKB();
      ApiClient.constructFromObject(data, obj, 'OrgTeamInner');
    }
    return obj;
  }
}
