/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TeamUserInner} from './TeamUserInner';

/**
 * The TeamUser model module.
 * @module model/TeamUser
 * @version 0.0.1
 */
export class TeamUser extends Array {
  /**
   * Constructs a new <code>TeamUser</code>.
   * @alias module:model/TeamUser
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TeamUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamUser} obj Optional instance to populate.
   * @return {module:model/TeamUser} The populated <code>TeamUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamUser();
      ApiClient.constructFromObject(data, obj, 'TeamUserInner');
    }
    return obj;
  }
}
