/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TeamQuestionInner} from './TeamQuestionInner';

/**
 * The TeamQuestion model module.
 * @module model/TeamQuestion
 * @version 0.0.1
 */
export class TeamQuestion extends Array {
  /**
   * Constructs a new <code>TeamQuestion</code>.
   * @alias module:model/TeamQuestion
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TeamQuestion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamQuestion} obj Optional instance to populate.
   * @return {module:model/TeamQuestion} The populated <code>TeamQuestion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamQuestion();
      ApiClient.constructFromObject(data, obj, 'TeamQuestionInner');
    }
    return obj;
  }
}
