/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {AuthWhoAmIResponse} from '../model/AuthWhoAmIResponse';

/**
* AuthWhoAmIResponse service.
* @module api/AuthWhoAmIResponseApi
* @version 0.0.1
*/
export class AuthWhoAmIResponseApi {

    /**
    * Constructs a new AuthWhoAmIResponseApi. 
    * @alias module:api/AuthWhoAmIResponseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the authWhoAmI operation.
     * @callback moduleapi/AuthWhoAmIResponseApi~authWhoAmICallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthWhoAmIResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * whoAmI
     * Check who is the current user
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt Authorization
     * @param {module:api/AuthWhoAmIResponseApi~authWhoAmICallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    authWhoAmI(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AuthWhoAmIResponse;

      return this.apiClient.callApi(
        '/api/auth/whoami', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}