/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {AuthLogin} from '../model/AuthLogin';
import {AuthLoginResponse} from '../model/AuthLoginResponse';

/**
* AuthLoginResponse service.
* @module api/AuthLoginResponseApi
* @version 0.0.1
*/
export class AuthLoginResponseApi {

    /**
    * Constructs a new AuthLoginResponseApi. 
    * @alias module:api/AuthLoginResponseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the authLogin operation.
     * @callback moduleapi/AuthLoginResponseApi~authLoginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthLoginResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * login
     * Login using user credentials
     * @param {module:model/AuthLogin} body Request body for controller.AuthLogin
     * @param {module:api/AuthLoginResponseApi~authLoginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    authLogin(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling authLogin");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AuthLoginResponse;

      return this.apiClient.callApi(
        '/api/auth/-/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the authRegister operation.
     * @callback moduleapi/AuthLoginResponseApi~authRegisterCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthLoginResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * register
     * Register a new Org account with OctoIQ
     * @param {module:model/AuthLogin} body Request body for controller.AuthLogin
     * @param {module:api/AuthLoginResponseApi~authRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    authRegister(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling authRegister");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AuthLoginResponse;

      return this.apiClient.callApi(
        '/api/auth/-/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}