/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Kb} from '../model/Kb';
import {KbCreate} from '../model/KbCreate';
import {KbUpdate} from '../model/KbUpdate';

/**
* Kb service.
* @module api/KbApi
* @version 0.0.1
*/
export class KbApi {

    /**
    * Constructs a new KbApi. 
    * @alias module:api/KbApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createKB operation.
     * @callback moduleapi/KbApi~createKBCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Kb{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * postKb
     * Create a new knowledge base
     * @param {module:model/KbCreate} body Request body for controller.KbCreate
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/KbApi~createKBCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createKB(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createKB");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Kb;

      return this.apiClient.callApi(
        '/api/kb/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getKB operation.
     * @callback moduleapi/KbApi~getKBCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Kb{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getKb
     * Get a specific knowledge base given a knowledge base ID
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/KbApi~getKBCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getKB(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getKB");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Kb;

      return this.apiClient.callApi(
        '/api/kb/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateKB operation.
     * @callback moduleapi/KbApi~updateKBCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Kb{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * putKb
     * Update a specific knowledge base given a knowledge base ID
     * @param {module:model/KbUpdate} body Request body for controller.KbUpdate
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/KbApi~updateKBCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateKB(body, id, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateKB");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateKB");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Kb;

      return this.apiClient.callApi(
        '/api/kb/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}