/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {OrgUser} from '../model/OrgUser';
import {OrgUserCreate} from '../model/OrgUserCreate';

/**
* OrgUser service.
* @module api/OrgUserApi
* @version 0.0.1
*/
export class OrgUserApi {

    /**
    * Constructs a new OrgUserApi. 
    * @alias module:api/OrgUserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createOrgUser operation.
     * @callback moduleapi/OrgUserApi~createOrgUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrgUser{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * postOrgUser
     * Create a user within the org given the Org ID
     * @param {module:model/OrgUserCreate} body Request body for controller.OrgUserCreate
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/OrgUserApi~createOrgUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createOrgUser(body, id, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createOrgUser");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling createOrgUser");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OrgUser;

      return this.apiClient.callApi(
        '/api/org/{id}/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getOrgUser operation.
     * @callback moduleapi/OrgUserApi~getOrgUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrgUser{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getOrgUser
     * Get a specific org user given the Org ID and the User ID
     * @param {String} id 
     * @param {String} userid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/OrgUserApi~getOrgUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getOrgUser(id, userid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getOrgUser");
      }
      // verify the required parameter 'userid' is set
      if (userid === undefined || userid === null) {
        throw new Error("Missing the required parameter 'userid' when calling getOrgUser");
      }

      let pathParams = {
        'id': id,'userid': userid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrgUser;

      return this.apiClient.callApi(
        '/api/org/{id}/users/{userid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getOrgUsers operation.
     * @callback moduleapi/OrgUserApi~getOrgUsersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrgUser{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllOrgUser
     * List all users in the org given the org ID
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/OrgUserApi~getOrgUsersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getOrgUsers(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getOrgUsers");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrgUser;

      return this.apiClient.callApi(
        '/api/org/{id}/users', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}