/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Room} from '../model/Room';

/**
* Room service.
* @module api/RoomApi
* @version 0.0.1
*/
export class RoomApi {

    /**
    * Constructs a new RoomApi. 
    * @alias module:api/RoomApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the deleteUserMessage operation.
     * @callback moduleapi/RoomApi~deleteUserMessageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Room{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllUserRooms
     * Delete a message given a user ID and message ID
     * @param {String} id 
     * @param {String} messageid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/RoomApi~deleteUserMessageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteUserMessage(id, messageid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUserMessage");
      }
      // verify the required parameter 'messageid' is set
      if (messageid === undefined || messageid === null) {
        throw new Error("Missing the required parameter 'messageid' when calling deleteUserMessage");
      }

      let pathParams = {
        'id': id,'messageid': messageid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Room;

      return this.apiClient.callApi(
        '/api/user/{id}/messages/{messageid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listUserRooms operation.
     * @callback moduleapi/RoomApi~listUserRoomsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Room{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllUserRooms
     * List all room a user is in given a user ID
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/RoomApi~listUserRoomsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listUserRooms(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling listUserRooms");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Room;

      return this.apiClient.callApi(
        '/api/user/{id}/rooms', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the messageUser operation.
     * @callback moduleapi/RoomApi~messageUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Room{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllUserRooms
     * Send a user a message given a user ID
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/RoomApi~messageUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    messageUser(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling messageUser");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Room;

      return this.apiClient.callApi(
        '/api/user/{id}/messages', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}