/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {TagManyCreate} from '../model/TagManyCreate';
import {TagManyResponse} from '../model/TagManyResponse';

/**
* TagManyResponse service.
* @module api/TagManyResponseApi
* @version 0.0.1
*/
export class TagManyResponseApi {

    /**
    * Constructs a new TagManyResponseApi. 
    * @alias module:api/TagManyResponseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createMultipleTags operation.
     * @callback moduleapi/TagManyResponseApi~createMultipleTagsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TagManyResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * postMultipleTag
     * Create multiple org tags
     * @param {module:model/TagManyCreate} body Request body for controller.TagManyCreate
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/TagManyResponseApi~createMultipleTagsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createMultipleTags(body, opts, callback) {
      opts = opts || {};
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createMultipleTags");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TagManyResponse;

      return this.apiClient.callApi(
        '/api/tag/multiple', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}