/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {TeamKB} from '../model/TeamKB';

/**
* TeamKB service.
* @module api/TeamKBApi
* @version 0.0.1
*/
export class TeamKBApi {

    /**
    * Constructs a new TeamKBApi. 
    * @alias module:api/TeamKBApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getTeamKB operation.
     * @callback moduleapi/TeamKBApi~getTeamKBCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamKB{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getTeamKB
     * Get a team knowledge base given a team ID and a knowledge base ID
     * @param {String} id 
     * @param {String} kbid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/TeamKBApi~getTeamKBCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getTeamKB(id, kbid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTeamKB");
      }
      // verify the required parameter 'kbid' is set
      if (kbid === undefined || kbid === null) {
        throw new Error("Missing the required parameter 'kbid' when calling getTeamKB");
      }

      let pathParams = {
        'id': id,'kbid': kbid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamKB;

      return this.apiClient.callApi(
        '/api/team/{id}/kb/{kbid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listTeamKB operation.
     * @callback moduleapi/TeamKBApi~listTeamKBCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamKB{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllTeamKB
     * Get a team Knowledge Base given a team ID
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/TeamKBApi~listTeamKBCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listTeamKB(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling listTeamKB");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamKB;

      return this.apiClient.callApi(
        '/api/team/{id}/kb', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}