/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {TeamQuestion} from '../model/TeamQuestion';

/**
* TeamQuestion service.
* @module api/TeamQuestionApi
* @version 0.0.1
*/
export class TeamQuestionApi {

    /**
    * Constructs a new TeamQuestionApi. 
    * @alias module:api/TeamQuestionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the listTeamKBQuestions operation.
     * @callback moduleapi/TeamQuestionApi~listTeamKBQuestionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamQuestion{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllTeamQuestions
     * List knowlege base questions for a team given a team ID, knowledge base ID
     * @param {String} id 
     * @param {String} kbid 
     * @param {Object} opts Optional parameters
     * @param {String} opts.jwt authorization
     * @param {module:api/TeamQuestionApi~listTeamKBQuestionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listTeamKBQuestions(id, kbid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling listTeamKBQuestions");
      }
      // verify the required parameter 'kbid' is set
      if (kbid === undefined || kbid === null) {
        throw new Error("Missing the required parameter 'kbid' when calling listTeamKBQuestions");
      }

      let pathParams = {
        'id': id,'kbid': kbid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TeamQuestion;

      return this.apiClient.callApi(
        '/api/team/{id}/kb/{kbid}/questions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}