/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApi);
  }
}(this, function(expect, OpenApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OrgUserInner', function() {
      beforeEach(function() {
        instance = new OpenApi.OrgUserInner();
      });

      it('should create an instance of OrgUserInner', function() {
        // TODO: update the code to test OrgUserInner
        expect(instance).to.be.a(OpenApi.OrgUserInner);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property isTermsConditions (base name: "is_terms_conditions")', function() {
        // TODO: update the code to test the property isTermsConditions
        expect(instance).to.have.property('isTermsConditions');
        // expect(instance.isTermsConditions).to.be(expectedValueLiteral);
      });

      it('should have the property orgsId (base name: "orgs_id")', function() {
        // TODO: update the code to test the property orgsId
        expect(instance).to.have.property('orgsId');
        // expect(instance.orgsId).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property teamsId (base name: "teams_id")', function() {
        // TODO: update the code to test the property teamsId
        expect(instance).to.have.property('teamsId');
        // expect(instance.teamsId).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
