/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApi);
  }
}(this, function(expect, OpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApi.KnowledgeBaseAPIApi();
  });

  describe('(package)', function() {
    describe('KnowledgeBaseAPIApi', function() {
      describe('createKB', function() {
        it('should call createKB successfully', function(done) {
          // TODO: uncomment, update parameter values for createKB call and complete the assertions
          /*
          var opts = {};

          instance.createKB(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Kb);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createKBQuestion', function() {
        it('should call createKBQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for createKBQuestion call and complete the assertions
          /*
          var opts = {};

          instance.createKBQuestion(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createVersionKBQuestion', function() {
        it('should call createVersionKBQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for createVersionKBQuestion call and complete the assertions
          /*
          var opts = {};

          instance.createVersionKBQuestion(id, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('dELETEApikbidquestionsqidtagstagidDeleteKbQuestionTag', function() {
        it('should call dELETEApikbidquestionsqidtagstagidDeleteKbQuestionTag successfully', function(done) {
          // TODO: uncomment, update parameter values for dELETEApikbidquestionsqidtagstagidDeleteKbQuestionTag call and complete the assertions
          /*
          var opts = {};

          instance.dELETEApikbidquestionsqidtagstagidDeleteKbQuestionTag(id, qid, tagid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteKB', function() {
        it('should call deleteKB successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteKB call and complete the assertions
          /*
          var opts = {};

          instance.deleteKB(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteKBQuestion', function() {
        it('should call deleteKBQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteKBQuestion call and complete the assertions
          /*
          var opts = {};

          instance.deleteKBQuestion(id, questionid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gETApikbidquestionsqidshareGetAllKbQuestionMagicLinks', function() {
        it('should call gETApikbidquestionsqidshareGetAllKbQuestionMagicLinks successfully', function(done) {
          // TODO: uncomment, update parameter values for gETApikbidquestionsqidshareGetAllKbQuestionMagicLinks call and complete the assertions
          /*
          var opts = {};

          instance.gETApikbidquestionsqidshareGetAllKbQuestionMagicLinks(id, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gETApikbidquestionsqidversionsGetKbQuestionVersions', function() {
        it('should call gETApikbidquestionsqidversionsGetKbQuestionVersions successfully', function(done) {
          // TODO: uncomment, update parameter values for gETApikbidquestionsqidversionsGetKbQuestionVersions call and complete the assertions
          /*
          var opts = {};

          instance.gETApikbidquestionsqidversionsGetKbQuestionVersions(id, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gETApikbidquestionsqidversionslatestGetKbQuestionLatest', function() {
        it('should call gETApikbidquestionsqidversionslatestGetKbQuestionLatest successfully', function(done) {
          // TODO: uncomment, update parameter values for gETApikbidquestionsqidversionslatestGetKbQuestionLatest call and complete the assertions
          /*
          var opts = {};

          instance.gETApikbidquestionsqidversionslatestGetKbQuestionLatest(id, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllKBQuestion', function() {
        it('should call getAllKBQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllKBQuestion call and complete the assertions
          /*
          var opts = {};

          instance.getAllKBQuestion(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getKB', function() {
        it('should call getKB successfully', function(done) {
          // TODO: uncomment, update parameter values for getKB call and complete the assertions
          /*
          var opts = {};

          instance.getKB(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Kb);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pOSTApikbidquestionsqidversionsPostKbQuestionVersion', function() {
        it('should call pOSTApikbidquestionsqidversionsPostKbQuestionVersion successfully', function(done) {
          // TODO: uncomment, update parameter values for pOSTApikbidquestionsqidversionsPostKbQuestionVersion call and complete the assertions
          /*
          var opts = {};

          instance.pOSTApikbidquestionsqidversionsPostKbQuestionVersion(id, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pUTApikbidquestionsqidtagstagidAssignKbQuestionTag', function() {
        it('should call pUTApikbidquestionsqidtagstagidAssignKbQuestionTag successfully', function(done) {
          // TODO: uncomment, update parameter values for pUTApikbidquestionsqidtagstagidAssignKbQuestionTag call and complete the assertions
          /*
          var opts = {};

          instance.pUTApikbidquestionsqidtagstagidAssignKbQuestionTag(id, qid, tagid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateKB', function() {
        it('should call updateKB successfully', function(done) {
          // TODO: uncomment, update parameter values for updateKB call and complete the assertions
          /*
          var opts = {};

          instance.updateKB(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Kb);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
