/*
 * OpenAPI
 * OpenAPI
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApi);
  }
}(this, function(expect, OpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApi.TeamAPIApi();
  });

  describe('(package)', function() {
    describe('TeamAPIApi', function() {
      describe('assignTeamQuestion', function() {
        it('should call assignTeamQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for assignTeamQuestion call and complete the assertions
          /*
          var opts = {};

          instance.assignTeamQuestion(id, kbid, qid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('assignTeamTag', function() {
        it('should call assignTeamTag successfully', function(done) {
          // TODO: uncomment, update parameter values for assignTeamTag call and complete the assertions
          /*
          var opts = {};

          instance.assignTeamTag(id, tagid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTeam', function() {
        it('should call createTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for createTeam call and complete the assertions
          /*

          instance.createTeam(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Team);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTeam', function() {
        it('should call deleteTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTeam call and complete the assertions
          /*
          var opts = {};

          instance.deleteTeam(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTeamTag', function() {
        it('should call deleteTeamTag successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTeamTag call and complete the assertions
          /*
          var opts = {};

          instance.deleteTeamTag(id, tagid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.UnknownInterface);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTeam', function() {
        it('should call getTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for getTeam call and complete the assertions
          /*
          var opts = {};

          instance.getTeam(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Team);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTeamKB', function() {
        it('should call getTeamKB successfully', function(done) {
          // TODO: uncomment, update parameter values for getTeamKB call and complete the assertions
          /*
          var opts = {};

          instance.getTeamKB(id, kbid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.TeamKB);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listTeamKB', function() {
        it('should call listTeamKB successfully', function(done) {
          // TODO: uncomment, update parameter values for listTeamKB call and complete the assertions
          /*
          var opts = {};

          instance.listTeamKB(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.TeamKB);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listTeamKBQuestions', function() {
        it('should call listTeamKBQuestions successfully', function(done) {
          // TODO: uncomment, update parameter values for listTeamKBQuestions call and complete the assertions
          /*
          var opts = {};

          instance.listTeamKBQuestions(id, kbid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.TeamQuestion);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listTeamTags', function() {
        it('should call listTeamTags successfully', function(done) {
          // TODO: uncomment, update parameter values for listTeamTags call and complete the assertions
          /*
          var opts = {};

          instance.listTeamTags(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.TeamTag);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listTeamUsers', function() {
        it('should call listTeamUsers successfully', function(done) {
          // TODO: uncomment, update parameter values for listTeamUsers call and complete the assertions
          /*
          var opts = {};

          instance.listTeamUsers(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.TeamUser);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTeam', function() {
        it('should call updateTeam successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTeam call and complete the assertions
          /*
          var opts = {};

          instance.updateTeam(body, id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApi.Team);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
